services:
  # for pulling updates and as a step development tool
  opschain-runner-devenv:
    scale: 0
    image: ${OPSCHAIN_RUNNER_IMAGE}
    volumes:
      - source: "${PROJECT_DIR}"
        target: /opt/opschain
        type: bind
      - source: ./opschain.lic
        type: bind
        target: /opschain.lic
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
