api:
  hostName: ${OPSCHAIN_API_HOST_NAME}
  ceritficateSecretName: ${OPSCHAIN_API_CERTIFICATE_SECRET_NAME}

sharedVolumes:
  projectGitRepos:
    storageClass: ${OPSCHAIN_SHARED_VOLUMES_STORAGE_CLASS}
    accessMode: "${OPSCHAIN_SHARED_VOLUMES_ACCESS_MODE}"
    size: 5Gi
  stepProperties:
    storageClass: ${OPSCHAIN_SHARED_VOLUMES_STORAGE_CLASS}
    accessMode: "${OPSCHAIN_SHARED_VOLUMES_ACCESS_MODE}"
    size: 1Gi

kong:
  namespace: "${OPSCHAIN_KUBERNETES_NAMESPACE}"
  image:
    tag: "${OPSCHAIN_IMAGE_TAG}"
  ingressController:
    watchNamespaces: [ "${OPSCHAIN_KUBERNETES_NAMESPACE}" ]
  proxy:
    http:
      servicePort: ${OPSCHAIN_API_EXTERNAL_PORT}
    tls:
      servicePort: ${OPSCHAIN_TLS_EXTERNAL_PORT}

trow:
  trow:
    domain: "${OPSCHAIN_IMAGE_REGISTRY_HOST}"
    password: "${OPSCHAIN_IMAGE_REGISTRY_PASSWORD}"
  volumeClaim:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: "${OPSCHAIN_IMAGE_REGISTRY_VOLUME_SIZE}"
  ingress:
    hosts:
      - paths: ['/']
        host: "${OPSCHAIN_IMAGE_REGISTRY_HOST}"
    tls:
      - secretName: opschain-image-registry-cert
        hosts:
          - "${OPSCHAIN_IMAGE_REGISTRY_HOST}"

sshKnownHostsConfigMapRef: "${OPSCHAIN_SSH_KNOWN_HOSTS_CONFIG_MAP}"

apiWorker:
  replicas: ${OPSCHAIN_API_WORKER_SCALE}

db:
  volume:
    storageClass: null
    accessMode: ReadWriteOnce
    size: 5Gi

ldap:
  volume:
    storageClassName: null
    accessMode: ReadWriteOnce
    size: 1Gi

buildService:
  rootless: ${OPSCHAIN_IMAGE_BUILD_ROOTLESS}
  volume:
    storageClass: null
    accessMode: ReadWriteOnce
    size: "${OPSCHAIN_IMAGE_BUILD_CACHE_VOLUME_SIZE}"

env:
  # OpsChain environment configuration
  OPSCHAIN_API_EXTERNAL_PORT: "${OPSCHAIN_API_EXTERNAL_PORT}"
  OPSCHAIN_API_WORKER_SCALE: "${OPSCHAIN_API_WORKER_SCALE}"
  OPSCHAIN_AUTH_SERVICE: "${OPSCHAIN_AUTH_SERVICE}"
  OPSCHAIN_CHANGE_LOG_RETENTION_DAYS: "${OPSCHAIN_CHANGE_LOG_RETENTION_DAYS}"
  OPSCHAIN_CLEAN_OLD_DATA_JOB_CRON: "${OPSCHAIN_CLEAN_OLD_DATA_JOB_CRON}"
  OPSCHAIN_CREATE_LOGS_API_PASSWORD: "${OPSCHAIN_CREATE_LOGS_API_PASSWORD}"
  OPSCHAIN_DETERMINISTIC_KEY: "${OPSCHAIN_DETERMINISTIC_KEY}"
  OPSCHAIN_DOCKER_PASSWORD: "${OPSCHAIN_DOCKER_PASSWORD}"
  OPSCHAIN_DOCKER_USER: "${OPSCHAIN_DOCKER_USER}"
  OPSCHAIN_EVENT_RETENTION_DAYS: "${OPSCHAIN_EVENT_RETENTION_DAYS}"
  OPSCHAIN_GID: "${OPSCHAIN_GID}"
  OPSCHAIN_IMAGE_REGISTRY_HOST: "${OPSCHAIN_IMAGE_REGISTRY_HOST}"
  OPSCHAIN_IMAGE_REGISTRY_PASSWORD: "${OPSCHAIN_IMAGE_REGISTRY_PASSWORD}"
  OPSCHAIN_IMAGE_TAG: "${OPSCHAIN_IMAGE_TAG}"
  OPSCHAIN_KEY_DERIVATION_SALT: "${OPSCHAIN_KEY_DERIVATION_SALT}"
  OPSCHAIN_KUBERNETES_NAMESPACE: "${OPSCHAIN_KUBERNETES_NAMESPACE}"
  OPSCHAIN_LDAP_ADMIN: "${OPSCHAIN_LDAP_ADMIN}"
  OPSCHAIN_LDAP_BASE_DN: "${OPSCHAIN_LDAP_BASE_DN}"
  OPSCHAIN_LDAP_CACHE_TTL: "${OPSCHAIN_LDAP_CACHE_TTL}"
  OPSCHAIN_LDAP_DOMAIN: "${OPSCHAIN_LDAP_DOMAIN}"
  OPSCHAIN_LDAP_ENABLE_SSL: "${OPSCHAIN_LDAP_ENABLE_SSL}"
  OPSCHAIN_LDAP_GROUP_ATTRIBUTE: "${OPSCHAIN_LDAP_GROUP_ATTRIBUTE}"
  OPSCHAIN_LDAP_GROUP_BASE: "${OPSCHAIN_LDAP_GROUP_BASE}"
  OPSCHAIN_LDAP_HC_USER: "${OPSCHAIN_LDAP_HC_USER}"
  OPSCHAIN_LDAP_HOST: "${OPSCHAIN_LDAP_HOST}"
  OPSCHAIN_LDAP_LOG_LEVEL: "${OPSCHAIN_LDAP_LOG_LEVEL}"
  OPSCHAIN_LDAP_ORGANISATION: "${OPSCHAIN_LDAP_ORGANISATION}"
  OPSCHAIN_LDAP_PASSWORD: "${OPSCHAIN_LDAP_PASSWORD}"
  OPSCHAIN_LDAP_PORT: "${OPSCHAIN_LDAP_PORT}"
  OPSCHAIN_LDAP_USER_ATTRIBUTE: "${OPSCHAIN_LDAP_USER_ATTRIBUTE}"
  OPSCHAIN_LDAP_USER_BASE: "${OPSCHAIN_LDAP_USER_BASE}"
  OPSCHAIN_LICENCE_ACCEPTED: "${OPSCHAIN_LICENCE_ACCEPTED}"
  OPSCHAIN_PRIMARY_KEY: "${OPSCHAIN_PRIMARY_KEY}"
  OPSCHAIN_RUNNER_IMAGE: "${OPSCHAIN_RUNNER_IMAGE}"
  OPSCHAIN_RUNNER_NAME: "${OPSCHAIN_RUNNER_NAME}"
  OPSCHAIN_RUNNER_NODE_SELECTOR: "${OPSCHAIN_RUNNER_NODE_SELECTOR}"
  OPSCHAIN_TLS_EXTERNAL_PORT: "${OPSCHAIN_TLS_EXTERNAL_PORT}"
  OPSCHAIN_UID: "${OPSCHAIN_UID}"
  PGPASSWORD: "${PGPASSWORD}"
  TZ: "${TZ}"
